### PR TITLE
Set up a "Hello Microverse" project (Day 2)

### PR DESCRIPTION
**Pull request by billymohajeri**
Set up a "Hello Microverse" project (Day 2)

In the 1st step, I added HTML and CSS files and updated README.md as requested.
After the first comment from the reviewer, I tried to solve the issue with linters.yml, .hintrc & .stylelintrc.json files and node_modules folder.

### CODE REVIEW

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - Professional README file. ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [x] I see that you added the `linters.yml` file in your project and that's working fine on Github, but in this project you need to add the linters configurations locally for learning purposes. Kindly add the `.hintrc` and the `.stylelintrc.json` files to your project and follow the tutorial in [this article](https://github.com/microverseinc/linters-config/tree/master/html-css) to make sure they are correctly installed.
- [x] The installation of the linters may add a `node_modules` folder, and this should be declared in the `.gitignore` file so this folder is not committed to the github repository. Please make sure this folder is correctly declared.
- [x] Your Pull Request should have a short summary describing the introduced changes in more detail. Please add that so the code reviewer can understand better the features and the purpose of this PR.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by sajid-munawar — CHANGES_REQUESTED** [review]
# Changes Required 
 ### Hi @billymohajeri ,
 Nice job, you are almost there.
 
 
 
 ## (Highlights) Good Points: 
 * Followed Github flow :heavy_check_mark:
 * No linter errors :heavy_check_mark: 

 ## (Changes Required) Aspects to improve: 
 *  ### Please do the following:
- [ ] As the previous reviewer mentioned, Please kindly add a more descriptive PR title.
### See a demo below:

https://user-images.githubusercontent.com/52934128/176308229-e31b2c8d-110b-4823-a2a8-31c1b7d7c73d.mp4



 ## [Optional] suggestions:
 * Nothing to mention.
 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @sajid-munawar in your question so I can receive the notification.
>
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by billymohajeri** [comment]
After the first comment from the reviewer, I tried to solve the issue with linters.yml, .hintrc & .stylelintrc.json files and node_modules folder.

**Review by levy002 — APPROVED** [review]
### Hello @billymohajeri 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
